### ISSUE TITLE
Support for different regions for S3 and Lambda

### ISSUE THREAD

**Issue by dhruvdutt** [benmarch/update-lambda-edge#5]
Currently, the `awsRegion` configured in the JSON file is used for both S3 bucket and Lambda.

Lambda@Edge has a [restriction](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/edge-functions-restrictions.html) that it should be deployed in `us-east-1`. Our S3 bucket is in a different region `ap-south-1`. Adding support to pass custom region for S3 and Lambda would help support such use-cases.

<img width="1696" alt="image" src="https://user-images.githubusercontent.com/5961873/176710280-534bca7f-115e-4a28-bf60-7f2c511bef95.png">

**Comment by dhruvdutt** [comment]
@benmarch Great work building this library and open-sourcing it. Happy to send a PR for this fix if you're willing to add support for this. 🙌

**Comment by benmarch** [comment]
Hey @dhruvdutt, thanks for the feature request! 

That's unfortunate, but I think you're right: it looks like `update-function-code` doesn't even accept a `region` parameter, which means it defaults to the one passed into the Lambda constructor when using the NodeJS SDK 🤔  I can run it by a colleague who might have some insight into this detail; I'll get back to you when I hear back.

**Comment by benmarch** [comment]
Ah ok, that should be possible. We could add a couple config params called "lambdaRegion" and "s3Region", and if they are specified it will download the ZIP and upload it directly to Lambda.

My one hesitation is that this adds quite a bit of complexity, and I think a simpler solution would be to create an S3 bucket in the same region as your Lambda. Is there a reason (maybe security or cost) that you wouldn't be able to do that? I can add the rationale to the README if we move forward with this feature. Thanks!

**Comment by dhruvdutt** [comment]
Yes, security and compliance is the reason (especially for fintechs). The region where we keep the code along with all previous versions must be in the region the company operates in for compliance reasons.

This could also be an issue for companies operating in EU regions probably depending on the source code of the Lambda (if it has anything user specific).

**Comment by benmarch** [comment]
Gotcha, let me see if I can whip something up. It might not be until the end of the week because we have a holiday here in the US, but I'll tag you in the PR when it's ready.

**Comment by benmarch** [comment]
@dhruvdutt I've opened #6 with the changes, and released it as version `1.2.0-rc.0` (or using the "next" tag: `npm i update-lambda-edge@next`). Please try it out and let me know if it works for you.

**Comment by benmarch** [comment]
@dhruvdutt just checking in, please let me know when you get a chance to test it out.

**Comment by dhruvdutt** [comment]
@benmarch Sorry, wasn't able to test this. We eventually moved to keep assets in the US region so this is not a blocker.
Thanks a lot for opening the PR ❤️  It's an important feature to have. I'll try to test this out for any new application that's upcoming in some time.

**Comment by benmarch** [comment]
Resolved with version 1.2.0.
